### ISSUE TITLE
Need a function to average expression values in each cluster

### ISSUE THREAD

**Issue by kriemo** [NCBI-Hackathons/clustifyR#11]

**Comment by tianchengzhe** [comment]
sapply(1:num_clust, function(x) Matrix::colMeans(A[,cluster==x]))

**Comment by tianchengzhe** [comment]
sorry, it should be rowMeans rather than colMeans

sapply(1:2, function(x) Matrix::rowMeans(A[,cluster==x]))

**Comment by agillen** [comment]
Implemented as `average_clusters()`.
