### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by kriemo** [NCBI-Hackathons/clustifyR#2]
`scmap` [code](https://github.com/hemberg-lab/scmap)  and [paper](https://www.nature.com/articles/nmeth.4644) and the related `scfind` [code](https://github.com/hemberg-lab/scfind)
`SingleR` [code](https://github.com/dviraran/SingleR) and [paper](https://doi.org/10.1101/284604)
`CellAtlasSearch` [paper](https://doi.org/10.1093/nar/gky421) no code available

**Comment by kriemo** [comment]
Here is a good resource for downloading bulk RNA-Seq data [Recount2](https://jhubiostatistics.shinyapps.io/recount/).

**Comment by YueYvetteHao** [comment]
GiniClust2: a cluster-aware, weighted ensemble clustering method for cell-type detection 
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1431-3

**Comment by YueYvetteHao** [comment]
Identification of cell types from single-cell transcriptomes using a novel clustering method (SNN) https://academic.oup.com/bioinformatics/article/31/12/1974/214505
