### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by kriemo** [NCBI-Hackathons/clustifyR#6]
SRP051688: https://www.ncbi.nlm.nih.gov//geo/query/acc.cgi?acc=GSE64655
  - Sorted human T and B cells, natural killer (NK) cells, myeloid dendritic cells (mDC), monocytes, and neutrophils from PBMCs. The day 0 controls are not perturbed.

**Comment by kriemo** [comment]
SRP053046: https://www.ncbi.nlm.nih.gov//geo/query/acc.cgi?acc=GSE65515
  - Sorted CD4+ T-Cells from healthy volunteers

**Comment by tianchengzhe** [comment]
B-Cells https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3106332/

**Comment by kriemo** [comment]
SRP062023: https://www.ncbi.nlm.nih.gov//geo/query/acc.cgi?acc=GSE58202
  - A single Megakaryocyte sample

**Comment by tianchengzhe** [comment]
https://www.nature.com/articles/s41598-017-01468-y

from skin. All cells vs. purified individual PBMC cell types.
probably can extract the relevant data.

**Comment by kriemo** [comment]
SRP048971: https://www.ncbi.nlm.nih.gov//geo/query/acc.cgi?acc=GSE62408
  - Purified populations from PBMCs

**Comment by YueYvetteHao** [comment]
public, human, RNA-seq experiments on PBMCs: http://www.cs.cmu.edu/~ckingsf/sharq/
[sra-PBMC-ids.txt](https://github.com/NCBI-Hackathons/RClusterCT/files/2124616/sra-PBMC-ids.txt)

**Comment by kriemo** [comment]
Pancreatic public data:

SRP056835 (a, b, and delta RNA-Seq from human fetal and adult)

**Comment by kriemo** [comment]
single cell rna seq resource: https://hemberg-lab.github.io/scRNA.seq.datasets/human/pancreas/
